### ISSUE TITLE
Users can make a decklist.

### ISSUE THREAD

**Issue by Derek-Cruz** [Derek-Cruz/ajax-project#1]
## 📐 Functionality

> The user needs to be able to make a deck list

## 🖼️ Wireframes

![Screenshot 2021-07-22 140358](https://user-images.githubusercontent.com/78568982/126709409-3d1f651e-be5c-4e30-a6af-0ebd1daaa345.png)

![Screenshot 2021-07-22 140433](https://user-images.githubusercontent.com/78568982/126709423-edce27dd-ed4c-4423-accf-99aa63bedfad.png)

## ✅ Task List

- [x] Add HTML 
- [x] Style CSS
- [x] Have cards show so you can add to deck list.
- [x] deck tab that shows cards you added
- [x] Remove unnecessary CSS
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
