### ISSUE TITLE
User can use the search bar

### ISSUE THREAD

**Issue by Derek-Cruz** [Derek-Cruz/ajax-project#10]
## ✅ Task List

- [x] Keydown listener for the search input
- [x] Search button has a click event for the search input
- [x] When the button is clicked you make the request to get the data.
- [x] Test in browser 
- [x] Clean up CSS
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
