### ISSUE TITLE
Users can browse and search cards.

### ISSUE THREAD

**Issue by Derek-Cruz** [Derek-Cruz/ajax-project#2]
## 📐 Functionality

The user can browse through all Magic the Gathering cards.

## 🖼️ Wireframes

![Screenshot 2021-07-22 140358](https://user-images.githubusercontent.com/78568982/126709875-50e5f070-8efc-44f3-8f4d-0692f72464f4.png)

![Screenshot 2021-07-22 140433](https://user-images.githubusercontent.com/78568982/126709881-f867815e-146c-42f3-a8b3-01a26fff4307.png)

## ✅ Task List

- [x] have next 100 cards show when incrementing or decrementing
- [x] have page remove the last 100 so only new cards show
- [x] Remove unnecessary CSS
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
